---
version: 2.1
jobs:
  test:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Test
          command: make test
      - store_test_results:
          path: dist
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Logging to Docker HUB
          command: >
            if [ "$DOCKERHUB_USERNAME" ] ; then
              echo "$DOCKERHUB_PASS" |
                docker login -u "$DOCKERHUB_USERNAME" --password-stdin ;
            fi
      - run:
          name: Installing qemu-utils
          command: sudo apt-get update; sudo apt-get install -y qemu-utils
      - run:
          name: Alpine Cache
          command: >
            make ${DOCKERHUB_USERNAME:+LINUXKIT_PKG_TARGET=push} FORCE_BUILD=--disable-cache pkg/alpine
      - run:
          name: Packages
          command: >
            make ${DOCKERHUB_USERNAME:+LINUXKIT_PKG_TARGET=push} FORCE_BUILD=--disable-cache pkgs
      - run:
          name: EVE
          command: >
            make ${DOCKERHUB_USERNAME:+LINUXKIT_PKG_TARGET=push EVE_SNAPSHOT_VERSION=0.0.0-snapshot} eve
      - store_artifacts:
          path: dist/amd64/installer/rootfs.img
      - store_artifacts:
          path: images/rootfs-xen.yml
  yetus:
    docker:
      - image: apache/yetus:0.12.0
    steps:
      - checkout
      # create a fake artifact so that Apache Yetus knows the URL
      - run:
          name: make artifact dir
          command: mkdir -p /tmp/yetus-out
      - run:
          name: bootstrap artifacts
          command: echo "bootstrap" > /tmp/yetus-out/bootstrap
      - store_artifacts:
          path: /tmp/yetus-out
      # now actually run Apache Yetus precommit
      - run:
          name: yetus
          command: make yetus
      - store_test_results:
          path: /tmp/yetus-out
      - store_artifacts:
          path: /tmp/yetus-out
workflows:
  version: 2.1
  build-stuff:
    jobs:
      - yetus
      - test
      - build
