state = "/run/containerd"
root = "/persist/containerd"
disabled_plugins = ["cri", "btrfs", "aufs"]

[grpc]
  address = "/run/containerd/containerd.sock"
  uid = 0
  gid = 0

[debug]
  address = "/run/containerd/debug.sock"
  level = "info"

[metrics]
  address = ""

[cgroup]
  path = "/eve/containerd"

[proxy_plugins]
  [proxy_plugins."eve.zfs.snapshotter"]
    type = "snapshot"
    address = "/run/eve.zfs.snapshotter.sock"
  [proxy_plugins."eve.overlay.snapshotter"]
    type = "snapshot"
    address = "/run/eve.overlay.snapshotter.sock"

# [plugins]
#  [plugins.content]
#    root = "/persist/vault/content"
