# Copyright (c) 2024-2025, Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0
---
name: Lint Commit Messages

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-stable"
      - "feature/*"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0

      - name: Fetch the PR's head ref
        run: |
          git fetch origin ${{ github.event.pull_request.head.sha }}:${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}

      - name: Create virtual environment
        run: |
          cd tools/check-commit-messages
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Lint commit messages
        run: |
          cd tools/check-commit-messages
          source .venv/bin/activate
          python check_commit_messages.py ${{ github.event.pull_request.base.sha }}
