# Copyright (c) 2026, Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0
---
name: CVE PR Gate

"on":
  pull_request:
    branches: ["master"]

jobs:
  cve-scan:
    name: Scan PR for Vulnerabilities
    uses: shjala/eve-cvewatch/.github/workflows/pr-scan.yml@v0.0.2
    with:
      eve-repo-url: ${{ github.event.pull_request.head.repo.clone_url }}
      eve-revision: ${{ github.event.pull_request.head.sha }}
