# Copyright (c) 2025, Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0
---
name: Go Tests
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-stable"
      - "feature/*"
    paths-ignore:
      - '**/*.md'
      - '.github/**'
  pull_request:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-stable"
      - "feature/*"
    paths-ignore:
      - '**/*.md'
      - '.github/**'

jobs:
  test:
    runs-on: zededa-ubuntu-2204
    steps:
      - name: Starting Report
        run: |
          echo Git Ref: ${GH_REF}
          echo GitHub Event: ${{ github.event_name }}
          echo Disk usage
          df -h
          echo Memory
          free -m
        env:
          GH_REF: ${{ github.ref }}
      - name: Clear repository
        run: |
          sudo rm -fr "$GITHUB_WORKSPACE" && mkdir "$GITHUB_WORKSPACE"
          rm -fr ~/.linuxkit
          docker system prune --all --force --volumes
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Login to Docker Hub
        if: ${{ github.event.repository.full_name == 'lf-edge/eve'}}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef  # v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_PULL_USER }}
          password: ${{ secrets.DOCKERHUB_PULL_TOKEN }}
      - name: Test
        run: |
          make test
      - name: Test (TPM Required)
        run: |
          bash tests/tpm/prep-and-test.sh
      - name: Report test results as Annotations
        if: ${{ always() }}
        uses: guyarb/golang-test-annoations@2941118d7ef622b1b3771d1ff6eae9e90659eb26  # v0.8.0
        with:
          test-results: dist/amd64/results.json
      - name: Store raw test results
        if: ${{ always() }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4  # v5.0.0
        with:
          name: 'test-report'
          path: ${{ github.workspace }}/dist
      - name: Get code coverage
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7  # v5.5.1
      - name: Clean
        if: ${{ always() }}
        run: |
          make clean || :
          docker system prune -f -a || :
          docker rm -f $(docker ps -aq) && docker volume rm -f $(docker volume ls -q) || :
          rm -rf ~/.linuxkit || :
